net375/theater-schedule-backend

TheaterDatabase/dbo/Tables/Schedule.sql, TheaterSchedule/Configurations/AccountConfiguration.cs, TheaterSchedule/Configurations/CreativeTeamMemberConfiguration.cs, TheaterSchedule/Configurations/GalleryImageConfiguration.cs, TheaterSchedule/Configurations/HashTagConfiguration.cs, TheaterSchedule/Configurations/HashTagPerformanceConfiguration.cs, TheaterSchedule/Configurations/PerformanceConfiguration.cs, TheaterSchedule/Configurations/PerformanceCreativeTeamMemberConfiguration.cs, TheaterSchedule/Configurations/ScheduleConfiguration.cs, TheaterSchedule/Configurations/SettingsConfiguration.cs, TheaterSchedule/Configurations/WatchlistConfiguration.cs, TheaterSchedule/Models/Account.cs, TheaterSchedule/Models/CreativeTeamMember.cs, TheaterSchedule/Models/GalleryImage.cs, TheaterSchedule/Models/HashTag.cs, TheaterSchedule/Models/HashTagPerformance.cs, TheaterSchedule/Models/Performance.cs, TheaterSchedule/Models/PerformanceCreativeTeamMember.cs, TheaterSchedule/Models/Schedule.cs, TheaterSchedule/Models/Settings.cs, TheaterSchedule/Models/TheaterScheduleContext.cs, TheaterSchedule/Models/Watchlist.cs, TheaterSchedule/TheaterSchedule.csproj, TheaterSchedule/appsettings.json
Generate Entity framework model for database.
Also implement loading of connection string from configuration file
Also created configuration files in Configuration folder.
Jira ticket: [LVNETZZZ-34 Generate Entity framework model for database](http://ssu-jira.softserveinc.com/browse/LVNETZZZ-34)
=> LVNETZZZ-34. Generate Entity framework model for database

TheaterDatabase/TheaterDatabase.sqlproj
=> Okrill-include-files-db added files to solution

TheaterSchedule.DAL/Models/PerformanceDataModel.cs, TheaterSchedule.DAL/Repositories/PerfomanceRepository.cs, TheaterSchedule/Startup.cs
Added datamodel file to slider endpoint
=> Added datamodel to slider endpoint

TheaterSchedule.DAL/Repositories/ScheduleRepository.cs
Add ScheduleId to ScheduleDataModel in ScheduleRepository.
=> Add ScheduleId to ScheduleDataModel

TheaterSchedule.BLL/DTO/SettingsDTO.cs, TheaterSchedule.BLL/Services/SettingsService.cs, TheaterSchedule.DAL/Repositories/LanguageRepository.cs, TheaterSchedule/Startup.cs, TheaterSchedule/appsettings.json.example
Fix language repository  after database update
=> Yurapav99 lvnetzzz 18 settings end po

TheaterDatabase/TheaterDatabase.sqlproj, TheaterDatabase/dbo/Tables/Message.sql, TheaterDatabase/dbo/Tables/Reply.sql, TheaterSchedule.BLL/DTO/MessageDTO.cs, TheaterSchedule.BLL/Interfaces/IMessageService.cs, TheaterSchedule.BLL/Services/MessageService.cs, TheaterSchedule.DAL/Interfaces/IMessageRepository.cs, TheaterSchedule.DAL/Repositories/MessageRepository.cs, TheaterSchedule/Controllers/MessageController.cs, TheaterSchedule/Startup.cs
Created endpoint for messages loading/storing
You can find this sub-task [here](https://ssu-jira.softserveinc.com/browse/LVNETZZZ-44)
=> LVNETZZZ-44. Create endpoint for messages loading/storing

TheaterDatabase/TheaterDatabase.sqlproj, TheaterDatabase/dbo/Tables/Language.sql, TheaterDatabase/dbo/Tables/PromoAction.sql, TheaterDatabase/dbo/Tables/PromoAction_TR.sql, TheaterSchedule.BLL/DTO/PromoActionDTO.cs, TheaterSchedule.BLL/Interfaces/IPromoActionService.cs, TheaterSchedule.BLL/Services/PromoActionService.cs, TheaterSchedule.DAL/Interfaces/IPromoActionRepository.cs, TheaterSchedule.DAL/Models/PerformanceDetailsDataModel.cs, TheaterSchedule.DAL/Models/PromoActionDataModel.cs, TheaterSchedule.DAL/Repositories/PerfomanceRepository.cs, TheaterSchedule.DAL/Repositories/PromoActionRepository.cs, TheaterSchedule/Controllers/PromoActionController.cs, TheaterSchedule/Startup.cs
=> Kril ostap lvnetzzz 36 promo action end point

TheaterSchedule.BLL/Services/MessageService.cs
Uncommented assigning to required field
=> Uncommented assigning to required field

TheaterSchedule.DAL/Repositories/ScheduleRepository.cs
Added left join for getting info about watchlist instead of inner join
=> LVNETZZZ-56. Fix method for getting schedule in repository

TheaterSchedule.DAL/Interfaces/ICreativeTeamRepository.cs, TheaterSchedule.DAL/Interfaces/ITagRepository.cs, TheaterSchedule.DAL/Models/PerformanceDataModel.cs, TheaterSchedule.DALwp/Repositories/CreativeTeamRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/PerfomanceRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/PerformanceDetailsRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/ScheduleRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/TagRepositoryWp.cs, TheaterSchedule.DALwp/TheaterSchedule.DALwp.csproj, TheaterSchedule.sln
=> Yurapav99 lvnetzzz 67 investigage integration with site

TheaterSchedule.BLL/Services/PostersService.cs, TheaterSchedule.DAL/Models/PerformanceDataModel.cs, TheaterSchedule.DALwp/Repositories/PerfomanceRepositoryWp.cs, TheaterSchedule/Startup.cs
created endpoints for performance repository wp
=> created endpoints for performance repository wp

TheaterSchedule.DALwp/Repositories/PerfomanceRepositoryWp.cs
Changed Repository for getting repertoire. Added pagination through pages in WordPress REST API from lvivpuppet.com
=> LVNETZZZ-103. Added loading of full repertoire looping through pages

TheaterSchedule.BLL/Services/PerformanceDetailsService.cs, TheaterSchedule.BLL/Services/PerformanceDetailsServiceWp.cs, TheaterSchedule.DALwp/Repositories/PerformanceDetailsRepositoryWp.cs, TheaterSchedule/TheaterSchedule.csproj, TheaterSchedule/appsettings.json.example
https://ssu-jira.softserveinc.com/browse/LVNETZZZ-109
Reworked loading of images (using new WP plugin)
=> Lvnetzzz 109. Rework loading of images

TheaterSchedule.BLL/DTO/PerformanceScheduleDTO.cs, TheaterSchedule.BLL/Interfaces/IPerformanceScheduleService.cs, TheaterSchedule.BLL/Services/PerformanceScheduleService.cs, TheaterSchedule.DAL/Interfaces/IPerformanceScheduleRepository.cs, TheaterSchedule.DAL/Models/PerformanceScheduleDataModel.cs, TheaterSchedule.DAL/Models/PerformanceScheduleDataModelBase.cs, TheaterSchedule.DALwp/Repositories/PerformanceScheduleRepositoryWp.cs, TheaterSchedule/Controllers/PerformanceScheduleController.cs, TheaterSchedule/Startup.cs
Added endpoint for schedule of specific performance loading with new acf-to-rest-api plugin;
Added memory cache;
=> Created endpoint for screen with schedule of specific performance

TheaterSchedule.DALwp/Repositories/PerformanceScheduleRepositoryWp.cs
Added error handling for specific schedule screen when schedule list is empty
=> Added error handling for specific schedule screen

TheaterSchedule.DALwp/Repositories/PerfomanceRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/PerformanceDetailsRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/PerformanceScheduleRepositoryWp.cs, TheaterSchedule.DALwp/Repositories/ScheduleRepositoryWp.cs
https://ssu-jira.softserveinc.com/browse/LVNETZZZ-127
=> LVNETZZZ-127. Resolved problem with apostrophe from WP

TheaterSchedule.BLL/Services/PerformanceDetailsServiceWp.cs
https://ssu-jira.softserveinc.com/browse/LVNETZZZ-128
=> LVNETZZZ-128. Fix cashing for isChecked in Performance Screen

TheaterSchedule/Controllers/PerformanceDetailsController.cs
=> Added swagger for PerformanceDetailsController

TheaterSchedule.BLL/Helpers/CacheProvider.cs, TheaterSchedule.BLL/Interfaces/ICacheProvider.cs, TheaterSchedule.BLL/Services/PerformanceScheduleService.cs, TheaterSchedule/Startup.cs
Fixed issue with memory caching in PerformanceSchedule Service
=> Fixed issue with memory caching in PerformanceSchedule Service

TheaterSchedule/Controllers/PerformanceScheduleController.cs
Added swagger documentation to PerformanceSchedule controller
=> Added swagger documentation to PerformanceSchedule controller

TheaterSchedule/Controllers/PostersController.cs
=> add swagger documentation to Posters

TeaterSchedule.DAL.Tests/LanguageRepositoryTest.cs, TeaterSchedule.DAL.Tests/TeaterSchedule.DAL.Tests.csproj, TheaterSchedule.sln
=> Unit tests for language repository were created

TeaterSchedule.DAL.Tests/EventRepositoryTest.cs
=> Unit tests for events repository were created

TheaterSchedule.BLL.Tests/PerformanceScheduleTest.cs, TheaterSchedule.BLL/TheaterSchedule.BLL.csproj
Added unit tests for PerformanceSchedule service
=> Added unit tests for PerformanceSchedule service

TheaterSchedule.BLL.Tests/PerformanceDetailsTest.cs, TheaterSchedule.BLL/Services/PerformanceDetailsServiceWp.cs, TheaterSchedule/Controllers/PerformanceDetailsController.cs
=> Added unit tests for PerformanceDetails service

TheaterSchedule.BLL/Services/PushNotificationsService.cs
=> Notification message was changed

TheaterDatabase/TheaterDatabase.refactorlog, TheaterDatabase/TheaterDatabase.sqlproj, TheaterDatabase/dbo/Tables/AdminsPost.sql, TheaterSchedule.BLL.Tests/AdminsPostServiceTest.cs, TheaterSchedule.BLL.Tests/Helpers/AdminsPostComparer.cs, TheaterSchedule.BLL/DTOs/AdminsPostDTO.cs, TheaterSchedule.BLL/Interfaces/IAdminsPostService.cs, TheaterSchedule.BLL/Services/AdminsPostService.cs, TheaterSchedule.DAL/Interfaces/IAdminsPostRepository.cs, TheaterSchedule.DAL/Repositories/AdminsPostRepository.cs, TheaterSchedule/Controllers/AdminsPostController.cs, TheaterSchedule/Controllers/MessageController.cs, TheaterSchedule/Properties/launchSettings.json, TheaterSchedule/Startup.cs
Added: 
- new table to database (AdminsPost)
- interfaces, repository, service, DTO
- controller
Basic unit tests for service. More will be coming later in different PR.
[LVNETA-142](https://ssu-jira.softserveinc.com/browse/LVNETA-142)
=> LVNETA-142 Create back-end part for sending messages

TheaterSchedule.BLL/DTOs/PushNotificationDTO.cs, TheaterSchedule.BLL/Services/PushNotificationsService.cs, TheaterSchedule.DAL/Models/PushTokenDataModel.cs, TheaterSchedule.DAL/Repositories/PushTokenRepository.cs, TheaterSchedule.DALwp/Repositories/ScheduleRepositoryWp.cs
lvneta-63
-edited models
-changed notification body to send an entire performance
-sending image url and notification color
=> Lvneta 63 working with notifications

TheaterDatabase/TheaterDatabase.sqlproj, TheaterSchedule.DAL/Repositories/GoogleFormUrlRepository.cs
Add possibility to rewrite link for google forms
=> Add possibility to rewrite link for google forms

TheaterSchedule.BLL/Interfaces/IPushNotificationsService.cs, TheaterSchedule.BLL/Services/PushNotificationsService.cs, TheaterSchedule.DAL/Interfaces/IPushTokenRepository.cs, TheaterSchedule.DAL/Repositories/PushTokenRepository.cs, TheaterSchedule/Controllers/AdminsPostController.cs, TheaterSchedule/Startup.cs
added sending push notifications when admin posts message, diffrerent notifications for private and public messages
=> added sending push notifications when admin post message

TheaterSchedule.BLL/DTOs/ApplicationUserDTO.cs, TheaterSchedule.BLL/Services/SettingsService.cs, TheaterSchedule/TheaterSchedule.csproj
Added fields validation on backend side
=> Added fields validation on backend side

TheaterSchedule.BLL/DTOs/ApplicationUserDTO.cs, TheaterSchedule.BLL/Services/UserService.cs, TheaterSchedule/Controllers/RegistrationController.cs, TheaterSchedule/Properties/launchSettings.json
daniukoi-UpdatedFieldsValidationAndRegistrationErrors
=> Updated fields validation and set back end part so it can properly handle

TheaterDatabase/TheaterDatabase.sqlproj, TheaterSchedule.BLL/Interfaces/IPerformanceDetailsService.cs, TheaterSchedule.BLL/Interfaces/IWishlistService.cs, TheaterSchedule.BLL/Services/PerformanceDetailsServiceWp.cs, TheaterSchedule.BLL/Services/WishlistService.cs, TheaterSchedule.DAL/Interfaces/IIsCheckedPerformanceRepository.cs, TheaterSchedule.DAL/Interfaces/IWishlistRepository.cs, TheaterSchedule.DAL/Repositories/IsCheckedPerformanceRepository.cs, TheaterSchedule.DAL/Repositories/WishlistRepository.cs, TheaterSchedule.DALwp/Repositories/PerformanceDetailsRepositoryWp.cs, TheaterSchedule/Controllers/ForgotPasswordController.cs, TheaterSchedule/Controllers/PerformanceDetailsController.cs, TheaterSchedule/Controllers/WishlistController.cs
=> Fixed wishlist bugs
